#!/bin/bash

#for f in out/*.txt; do
#    filename=$(basename "$f")
#    filename="${filename%.*}"
#    echo $filename
#    gnuplot -e "filename='$filename'" sod.plt
#done


ffmpeg -framerate 30 -i out/out_%04d.png -c:v libx264 -r 30 -pix_fmt yuv420p -y out.mp4
