#!/bin/bash

for f in out/*.txt; do
    filename=$(basename "$f")
    filename="${filename%.*}"

    echo $filename
    gnuplot -e "filename='$filename'" sod.plt
done


ffmpeg -framerate 40 -i out/out_%03d.png -c:v libx264 -r 30 -pix_fmt yuv420p -y out.mp4
